import type { IndustryConfigInput } from './types';

export const DEFAULT_INDUSTRY_CONFIGS: IndustryConfigInput[] = [
  {
    name: '化工原料产业',
    category: '原材料工业',
    subCategory: '化工原料',
    description: '关注安全事故、危化品监管、环保处罚、园区停产、限产整改等风险事件，适合做事件时间轴和高风险预警。',
    keywords: ['爆炸', '泄漏', '环保督察', '停产整顿'],
    riskTerms: ['安全事故', '危化品监管', '环保处罚', '园区停产', '限产整改'],
    regions: ['全国', '重点化工园区'],
    entities: ['化工园区', '危化品企业', '生态环境部门', '应急管理部门'],
    sourceTypes: ['authority', 'news', 'social', 'wechat'],
    alertLevel: '高风险预警',
    isEnabled: true,
  },
  {
    name: '煤炭产业',
    category: '能源产业',
    subCategory: '煤炭',
    description: '关注安全生产、价格波动、供应紧张、矿山事故和监管检查，适合做市场波动与区域风险监控。',
    keywords: ['煤价', '矿难', '安全检查', '停产'],
    riskTerms: ['安全生产', '价格波动', '供应紧张', '矿山事故', '监管检查'],
    regions: ['全国', '重点煤炭产区'],
    entities: ['煤矿企业', '矿山监管部门', '能源局', '煤炭交易中心'],
    sourceTypes: ['authority', 'news', 'social', 'wechat'],
    alertLevel: '重点关注',
    isEnabled: true,
  },
  {
    name: '食品加工产业',
    category: '消费品工业',
    subCategory: '食品加工',
    description: '关注食品安全、环保处罚、产品召回、停产整改和市场监管，优先从监管公告等权威源采集。',
    keywords: ['食品安全', '抽检不合格', '召回', '处罚'],
    riskTerms: ['食品安全', '环保处罚', '产品召回', '停产整改', '市场监管'],
    regions: ['全国', '重点食品加工园区'],
    entities: ['食品加工企业', '市场监管部门', '生态环境部门', '消费者协会'],
    sourceTypes: ['authority', 'news', 'social', 'wechat'],
    alertLevel: '重点关注',
    isEnabled: true,
  },
  {
    name: '水产/海参养殖',
    category: '农林牧渔',
    subCategory: '水产养殖',
    description: '关注赤潮、疫病、禁养区、环保治理、价格波动和极端天气，适合做地区加产业的异常发现。',
    keywords: ['赤潮', '死鱼', '禁养', '病害'],
    riskTerms: ['赤潮', '疫病', '禁养区', '环保治理', '价格波动', '极端天气'],
    regions: ['全国', '沿海养殖区'],
    entities: ['养殖企业', '渔业主管部门', '海洋预报机构', '农业农村部门'],
    sourceTypes: ['authority', 'news', 'social', 'wechat'],
    alertLevel: '一般关注',
    isEnabled: true,
  },
  {
    name: '纺织/鞋帽针织',
    category: '轻工制造',
    subCategory: '纺织服装',
    description: '关注订单波动、外贸政策、环保整治、工厂停工和用工风险，适合监控产业景气度变化。',
    keywords: ['外贸订单', '停工', '环保整治', '出口'],
    riskTerms: ['订单波动', '外贸政策', '环保整治', '工厂停工', '用工风险'],
    regions: ['全国', '重点外贸产业带'],
    entities: ['纺织企业', '鞋帽企业', '外贸企业', '商务部门'],
    sourceTypes: ['authority', 'news', 'social', 'wechat'],
    alertLevel: '一般关注',
    isEnabled: true,
  },
];
